language: android
jdk:
- oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.0
  - android-25
  - extra-google-m2repository
  - extra-android-m2repository
sudo: false
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
script:
- ./gradlew build jacocoTestReport
after_success:
- bash <(curl -s https://codecov.io/bash)
